name: flutter_ume_plus
description: UME is an in-app debug kits platform for Flutter apps. Produced by Flutter Infra team of ByteDance.
version: 5.2.1
homepage: https://github.com/mdddj/flutter_ume
repository: https://github.com/mdddj/flutter_ume

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.5.5
  vm_service: ^15.1.0
  tuple: ^2.0.2
  vibration: ^3.1.8

dev_dependencies:
  mockito: ^5.6.4
  lints: ^6.1.0
  flutter_lints: ^6.0.0


