name: flutter_ume_kit_dio_plus
description: Dio kit for flutter_ume.
version: 5.2.2
homepage: https://github.com/mdddj/flutter_ume
repository: https://github.com/mdddj/flutter_ume

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ume_plus: "<=5.2.0"
  dio: ^5.9.2

dev_dependencies:
  flutter_lints: ^6.0.0

